spring.application.name=moneymanager
server.port=8081
# MongoDB
server.port=8080
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=money_manager

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html